name: Public Relations for Self Published Authors
favicon: null
layout_spectrum: 0.29838997847400606
typography_spectrum: 0.9763178818393499
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8269834527745843
  lightness: 0.7286451775580645
  saturation: 0.5651564518921077
  rhythmicContrast: 0.9456472913734615
purpose: []
