name: Public Relations for Self Published Authors
favicon: null
layout_spectrum: 0.60853
typography_spectrum: 0.38745
title: Find the tools you need to market yourself and manage your brand as an author
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3125
  lightness: 0.9375
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
